name: absensiswa
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  hexcolor: 3.0.1
  google_fonts: 3.0.1
  iconly: 1.0.1
  iconsax: 0.0.8
  ionicons: 0.2.1
  lottie: 2.0.0
  easy_splash_screen: 1.0.4
  get_storage: 2.0.3
  moor_flutter: 4.1.0
  group_radio_button: 1.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  moor_generator: 4.6.0+1
  build_runner: 2.3.2
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

